name: HTML

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Get ontology version
      run: |
           pip install rdflib
           echo "ONTO_VERSION=$(python main/.github/workflows/get_version.py)" >> "$GITHUB_ENV"
    - name: Build HTML for main
      run: | 
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
           mkdir public 
           mkdir public/v$ONTO_VERSION
           java -jar widoco.jar -ontFile main/ontology.ttl -outFolder public/v$ONTO_VERSION -htaccess -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           cp public/v$ONTO_VERSION/index-en.html public/v$ONTO_VERSION/index.html
           ln -s public/v$ONTO_VERSION public/latest
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
