name: OOPS

on:
  push:
    branches:
    - develop
jobs:
  oops:
    runs-on: ubuntu-latest
    steps:
    ## First step: Checkout main from the repository
    - uses: actions/checkout@v3
      with:
        ref: develop
        path: main
    ## Second step: Get report from OOPS API
    - name: Get report from OOPS API
      run: |
           pip install rdflib
           python main/.github/workflows/oops_report.py --ontology-file main/ontology.ttl --ontology-file-type turtle --restriction https://example.org --verbose
           ls -la .
    - name: Keep oops report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: oops_report
        path: report.json
