name: OOPS

on:
  push:
    branches:
    - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    ## First step: Checkout main from the repository
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    ## Second step: Get report from OOPS API
    - name: Get report from OOPS API
      run: |
           pip install rdflib
           echo "OOPS_MAXLEVEL=$(python main/.github/workflows/oops_report.py --ontology-file main/ontology.ttl --ontology-file-type turtle --resctriction https://example.org)" >> "$GITHUB_ENV"
