name: Release

on:
  push:
    branches:
    - main
jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: MattTJung_Patch-1
        path: release_main
    - name: Get ontology version
      id: get_onto_version
      run: |
           pip install rdflib
           ontoversion=$(python release_main/.github/workflows/get_ontoversion.py)
           echo "Got version from python script: $ontoversion"
           echo "V_ONTO_VERSION=$ontoversion" >> $GITHUB_ENV
    - name: Check if release exists
      run: |
           cd release_main
           if gh release view "v$V_ONTO_VERSION" -R "$GITHUB_REPOSITORY" &> /dev/null; then
             echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
           else
             echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
           fi
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Delete old release if it exists
      if: env.RELEASE_EXISTS == 'true'
      run : |
            cd release_main
            gh release delete "v$V_ONTO_VERSION" -y --cleanup-tag
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Create Release
      run: |
           cd release_main
           echo "V_ONTO_VERSION: $V_ONTO_VERSION"
           gh release create "v$V_ONTO_VERSION" --title "Release $V_ONTO_VERSION" --notes "Release $V_ONTO_VERSION"
      env:
        GH_TOKEN: ${{ github.token }}
