name: shacl validation

on:
  push:
    branches:
    - develop_shapes
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: main
    - name: Validate against SHACL shape
      run: |
           #ls -la
           pip install pyshacl

           curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
           #java -jar robot.jar --version

           
           java -jar robot.jar reason --reasoner hermit --input main/ontology.ttl --output out_ontology-reasoned.ttl
           python3 -m pyshacl -f turtle -o ./out_shacl_report.ttl -s main/shapes.ttl out_ontology-reasoned.ttl
    - name: Keep report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: ./out_*
