name: develop_multiontofiles Workflow

on:
  push:
    branches:
    - dev*
jobs:
  oops_report:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: combine_onto_files
      - name: combine ontology files and remove obsolete imports
        run: |
             mkdir out
             python -m pip install rdflib
             python combine_onto_files/.github/workflows/combine_onto_files.py -o out/combined.ttl --rdfout out/combined.rdf combine_onto_files/ontology.ttl combine_onto_files/moduleA.ttl combine_onto_files/moduleB.ttl
      - name: generate oops request xml
        run: |
             python combine_onto_files/.github/workflows/generate_oops_request_content.py -o out/oops_request.xml -i out/combined.rdf
      - name: call oops api
        run: |
             curl -o out/oops_response.xml -X POST -L -H "Content-Type: application/xml" -d @out/oops_request.xml https://oops.linkeddata.es/rest
      - name: generate oops report
        run: |
             mkdir -p pages/$GITHUB_REF_NAME/oops_report
             cp combine_onto_files/.github/workflows/oops_report/* pages/$GITHUB_REF_NAME/oops_report
             mv pages/$GITHUB_REF_NAME/oops_report/show_oops_response.html pages/$GITHUB_REF_NAME/oops_report/index.html
             cp out/oops_response.xml pages/$GITHUB_REF_NAME/oops_report
      - name: generate artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined_ontologies
          path: out
      - name: generate artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages
          path: pages
      - name: publish to github-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: pages
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  html_doc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: build_html_doc
      - name: build html doc for all ttl files
        run: |
          wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
          mkdir -p html_out/$GITHUB_REF_NAME/ontology
          mkdir -p html_out/$GITHUB_REF_NAME/moduleA
          mkdir -p html_out/$GITHUB_REF_NAME/moduleB
          java -jar widoco.jar -ontFile build_html_doc/ontology.ttl -outFolder html_out/$GITHUB_REF_NAME/ontology -uniteSections -includeAnnotationProperties -lang en-de -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
          cp html_out/$GITHUB_REF_NAME/ontology/index-en.html html_out/$GITHUB_REF_NAME/ontology/index.html
          java -jar widoco.jar -ontFile build_html_doc/moduleA.ttl -outFolder html_out/$GITHUB_REF_NAME/moduleA -uniteSections -includeAnnotationProperties -lang en-de -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
          cp html_out/$GITHUB_REF_NAME/moduleA/index-en.html html_out/$GITHUB_REF_NAME/moduleA/index.html
          java -jar widoco.jar -ontFile build_html_doc/moduleB.ttl -outFolder html_out/$GITHUB_REF_NAME/moduleB -uniteSections -includeAnnotationProperties -lang en-de -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
          cp html_out/$GITHUB_REF_NAME/moduleB/index-en.html html_out/$GITHUB_REF_NAME/moduleB/index.html
      - name: generate artifact
        uses: actions/upload-artifact@v4
        with:
          name: html_doc
          path: build_html_doc
      - name: publish to github-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: html_out
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}