name: Deploy

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: github.ref_name == 'main'
    steps:
    - uses: MattTJung/action_onto_doc@develop
      with:
        ontology-file-path: ontology.ttl
        ontology-name: 'ont_pub_tmplt'
        github-token: ${{ secrets.GITHUB_TOKEN }}