name: develop_multiontofiles Workflow

on:
  push:
    branches:
    - develop_multiontofiles
jobs:
  combine_onto_files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: combine_onto_files
      - name: combine ontology files and remove obsolete imports
        run: |
             mkdir out
             python -m pip install rdflib
             python combine_onto_files/.github/workflows/combine_onto_files.py -o out/combined.ttl --rdfout out/combined.rdf combine_onto_files/ontology.ttl combine_onto_files/moduleA.ttl combine_onto_files/moduleB.ttl
      - name: generate oops request xml
        run: |
             python combine_onto_files/.github/workflows/generate_oops_request_content.py -o out/oops_request.xml -i out/combined.rdf
      - name: call oops api
        run: |
             curl -o out/oops_response.xml -X POST -L -H "Content-Type: application/xml" -d @out/oops_request.xml https://oops.linkeddata.es/rest
      - name: generate oops report
        run: |
             mkdir pages
             mkdir pages/oops_report
             cp combine_onto_files/.github/workflows/oops_report/* pages/oops_report
             mv pages/oops_report/show_oops_response.html pages/oops_report/index.html
             cp out/oops_response.xml pages/oops_report
      - name: generate artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined_ontolgies
          path: out
      - name: generate artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-new
          path: pages
      - name: publish to github-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}